spring.application.name=demo

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

server.port=10000

api.security.token.secret=${JWT_SECRET:secret-key}

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.datasource.hikari.connection-init-sql=SET SESSION CHARACTERISTICS AS TRANSACTION READ WRITE
spring.jpa.properties.hibernate.jdbc.use_get_generated_keys=true
spring.jpa.properties.hibernate.query.in_clause_parameter_padding=true

logging.level.org.springframework.security=DEBUG

spring.datasource.hikari.initializationFailTimeout=0
spring.datasource.hikari.connectionTimeout=60000
spring.datasource.hikari.validationTimeout=5000
spring.jpa.defer-datasource-initialization=true
