spring.application.name=demo

spring.datasource.url=jdbc:postgresql://db.sveuvfwxshlnhhfwiwsm.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=cLZY2E6nQleY9JHp
spring.datasource.driver-class-name=org.postgresql.Driver
logging.level.org.springframework.security=DEBUG
api.security.token.secret=${JWT_SECRET:secret-key}

spring.jpa.show-sql=true