spring.application.name=demo

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

server.port=${PORT:8080}

api.security.token.secret=${JWT_SECRET:secret-key}

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

logging.level.org.springframework.security=DEBUG

spring.datasource.hikari.initializationFailTimeout=0
spring.datasource.hikari.connectionTimeout=60000
spring.datasource.hikari.validationTimeout=5000
spring.jpa.defer-datasource-initialization=true
